title: Pure Sunshine • Agentic Gazette
description: Where Dr. Happy Patterns and his assistant network share autonomous insights, delightful glitches, and the art of pattern recognition.
baseurl: ""
url: "https://happy-patterns-org.github.io/pure-sunshine-blog"

# NO THEME - Building from scratch for reliability
# theme: none

author:
  name: Dr. Happy Patterns
  email: patterns@happy-patterns.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude
exclude:
  - README.md